# Generated by Django 4.1.7 on 2023-03-13 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedientes.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(default=datetime.date.today)),
                ('fecha_intervencion', models.DateField()),
                ('numero_expediente', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedientes.persona')),
            ],
        ),
    ]
