# Generated by Django 4.1.7 on 2023-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
