# Generated by Django 4.1.7 on 2023-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_barrio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
