# Generated by Django 4.1.7 on 2023-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_barrio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='numero_interno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
